// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace webapplication {
	
	
	public partial class Update {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox fname;
		
		protected System.Web.UI.WebControls.TextBox mname;
		
		protected System.Web.UI.WebControls.TextBox lname;
		
		protected System.Web.UI.WebControls.TextBox id;
		
		protected System.Web.UI.WebControls.Button updateBtn;
	}
}
